prim_clr="#2D3250"
err_clr="#A0153E"
scndry_clr="white"
gradient_clrs=["#7077A1","#424769",prim_clr,]
highlight_clr="#F6B17A"
fade_clr="Grey400"
prim_font="Lalezar"
border_clr="Grey300"

ElevatedBtn_style={
    "color":prim_clr,
    "bgcolor":scndry_clr,
}
ElevatedBtn_style2={
    "color":scndry_clr,
    "bgcolor":prim_clr,
}
alrt_dlg_title_style={
    "text_align":"right",
    "color":scndry_clr,
    "font_family":prim_font,
}
